# Generated by Django 5.0.6 on 2024-05-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=20)),
                ('Product_Code', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=8)),
                ('Fabric_Type', models.CharField(choices=[('Natural', 'Natural'), ('Synthetic', 'Synthetic'), ('Semi-Synthetic', 'Semi-synthetic')], max_length=25)),
                ('Free_Size', models.BooleanField(default=False)),
            ],
        ),
    ]
