# Generated by Django 5.0.6 on 2024-05-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
